M48
; DRILL file KiCad 10.0.3 date 2026-06-01T12:07:49
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-06-01T12:07:49+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.3
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X99.16Y-96.56
X99.16Y-102.34
X99.16Y-109.91
X99.16Y-115.69
T2
X96.9Y-86.65
X151.85Y-86.7
M30
